fix context and missing vcHolder implementations
w3c/vc-di-ecdsa-test-suite pull request #109
Opened 2024-12-06 17:33 UTC by PatStLouis

2024-12-10 17:48 UTC, BigBlueHat approved these changes
I like the simplification! I would like skip messages if possible, but merge this first, if you want.

2024-12-12 19:50 UTC, TallTed requested changes
Tiny things

2024-12-12 19:50 UTC, TallTed commented on tests/95-functions-sd.js
> +            'Derive endpoint should reject proof without multibase indicator.'
```suggestion
            'Derived endpoint should reject proof without multibase indicator.'
```

2024-12-12 19:50 UTC, TallTed commented on tests/95-functions-sd.js
> +            'Derive endpoint should reject proof without header.'
```suggestion
            'Derived endpoint should reject proof without header.'
```

2024-12-13 15:37 UTC, PatStLouis commented
@TallTed Thank you for the edits/suggestion, I've committed them. Please approve the corrections so we can merge this PR.

2024-12-13 17:01 UTC, dlongley commented on tests/95-functions-sd.js
> +            'Derived endpoint should reject proof without header.'
```suggestion
            'Derive endpoint should reject proof without header.'
```

2024-12-13 17:01 UTC, dlongley commented on tests/95-functions-sd.js
> +            'Derived endpoint should reject proof without multibase indicator.'
This is the `/derive` endpoint:

```suggestion
            'Derive endpoint should reject proof without multibase indicator.'
```

2024-12-13 17:18 UTC, PatStLouis commented
@TallTed since @dlongley pointed out the the word "Derive" was referring to the "Derive endpoint", the past tense doesn't apply since this is now a noun designating a thing. I've had to revert the suggestions. Could you approve this please?
https://w3c-ccg.github.io/vc-api/#derive-credential

2024-12-13 17:20 UTC, dlongley approved these changes

2024-12-17 20:12 UTC, TallTed commented on tests/95-functions-sd.js
> +            'Derive endpoint should reject proof without multibase indicator.'
```suggestion
            '"Derive" endpoint should reject proof without multibase indicator.'
```

2024-12-17 20:12 UTC, TallTed commented on tests/95-functions-sd.js
> +            'Derive endpoint should reject proof without header.'
```suggestion
            '"Derive" endpoint should reject proof without header.'
```

2024-12-17 20:13 UTC, msporny approved these changes

2024-12-17 20:14 UTC, TallTed approved these changes

2024-12-17 20:18 UTC, merged