Throw in interop if no vc
w3c/vc-di-ecdsa-test-suite pull request #32
Opened 2024-01-29 21:45 UTC by aljones15

Currently the interop tests will just pass an empty credential to a verifier if the an issuer fails to issue a Vc.
This PR fixes that, by throwing so that in the interop report an implementer will see that the interop issue
occurred because the issuer of the Vc failed and not their verifier itself.

2024-01-29 21:49 UTC, TallTed requested changes

2024-01-29 21:49 UTC, TallTed commented on CHANGELOG.md
> +- Interop tests throw if the issuer fails to issue a Vc.
```suggestion
- Interop tests throw if the issuer fails to issue a VC.
```

2024-01-29 21:49 UTC, TallTed commented on tests/30-rdfc-interop.js
> +            `Expected issuer ${issuerDisplayName} to issue a Vc.`
```suggestion
            `Expected issuer ${issuerDisplayName} to issue a VC.`
```

2024-01-29 21:49 UTC, TallTed commented on tests/60-sd-interop.js
> +            `Expected issuer ${issuerDisplayName} to issue a disclosed Vc.`
```suggestion
            `Expected issuer ${issuerDisplayName} to issue a disclosed VC.`
```

2024-01-30 02:08 UTC, Wind4Greg approved these changes
This is helpful!

2024-01-30 12:51 UTC, merged