Expand Usage section of README for Filtering, Local testing, and test…
w3c/vc-di-ecdsa-test-suite pull request #34
Opened 2024-02-01 20:14 UTC by aljones15

… tag changes.

2024-02-03 15:35 UTC, Wind4Greg approved these changes

2024-02-05 15:52 UTC, TallTed requested changes

2024-02-05 15:52 UTC, TallTed commented on README.md
> +This suite uses [mocha.js](https://mochajs.org) as the test runner.
```suggestion
This suite uses [`mocha.js`](https://mochajs.org) as the test runner.
```

2024-02-05 15:52 UTC, TallTed commented on README.md
> +For example, the snippet below uses grep to filter tests by name and only runs one of the test suites.
```suggestion
For example, the snippet below uses `grep` to filter tests by name, and only runs one of the test suites.
```

2024-02-05 15:52 UTC, TallTed commented on README.md
> +After adding the config file, both the localhost implementations and other
```suggestion
After adding the configuration file, both the localhost implementations and other
```

2024-02-05 15:52 UTC, TallTed commented on README.md
> +the config above, you can adjust the tag used in each test suite by modifying `./config/runner.json`
```suggestion
For instance, if your `.localImplementationsConfig.cjs` configuration file looks like
the one above, you can adjust the tag used in each test suite by modifying `./config/runner.json`
```

2024-02-05 18:35 UTC, merged