Port mocks to VC 2.0 context.
w3c/vc-di-ecdsa-test-suite pull request #51
Opened 2024-03-01 13:44 UTC by aljones15

This ports the existing mock data to the VC 2.0 Context.

2024-03-01 21:45 UTC, aljones15 commented
this should be good to go once new VC 2.0 compatible ecdsa instances are up.

2024-03-02 00:48 UTC, tminard approved these changes

2024-03-06 15:55 UTC, BigBlueHat approved these changes

2024-03-07 16:15 UTC, BigBlueHat requested changes
Actually...this is a bigger piece of work... We don't want to drop support for v1.1, so we need fixtures/mocks for both and to use them concurrently.

2024-03-28 15:21 UTC, aljones15 commented
closing in favor of: https://github.com/w3c/vc-di-ecdsa-test-suite/pull/58

2024-03-28 15:21 UTC, closed without merging