Use localVerifier for SD tests.
w3c/vc-di-ecdsa-test-suite pull request #68
Opened 2024-04-02 20:44 UTC by tminard

2024-04-02 22:37 UTC, aljones15 commented on tests/40-sd-create.js
> +                const derivedCredential = await jsigs.derive(issuedVc, {
there is an existing deriveCredential function in `vc-generator` used for the sd-verify test data.

2024-04-02 22:38 UTC, aljones15 requested changes
the vc-generator's derive stuff should handle the derivation and remove some of these new imports in this file. Aside from that good work and really impressed with this.

2024-04-03 12:25 UTC, aljones15 commented on tests/40-sd-create.js
> +                const derivedCredential = await jsigs.derive(issuedVc, {
also might want to add a comment about how anyone can derive a proof from a base proof.

2024-04-03 18:04 UTC, tminard commented on tests/40-sd-create.js
> +            it('The "proof" MUST verify with a conformant verifier.',
No I do not see any specific normative statements that would mandate this test: https://w3c.github.io/vc-di-ecdsa/#add-derived-proof-ecdsa-sd-2023

Perhaps it is safe to delete?

It seems more like an integration test that is helpful to verify your specific implementation produces a "valid" credential, but it does not have a link in the spec that I could find.

2024-04-03 23:25 UTC, aljones15 approved these changes
Let's get this and finish off the ECDSA stuff.

2024-04-04 00:38 UTC, merged