Update report title.
w3c/vc-di-ecdsa-test-suite pull request #79
Opened 2024-05-02 15:46 UTC by BigBlueHat

Old title was specific to a single cryptosuite, but these tests
now include tests for three ECDSA cryptosuites.

2024-05-02 20:01 UTC, TallTed requested changes

2024-05-02 20:01 UTC, TallTed commented on README.md
> +// localConfig.cjs defining local implementations
```suggestion
// localConfig.cjs defines local implementations
```

2024-05-02 20:01 UTC, TallTed commented on README.md
>  // you can specify a BASE_URL before running the tests such as:
```suggestion
// you can specify a BASE_URL when running the tests such as:
```

2024-05-24 12:21 UTC, aljones15 approved these changes
Provided the suggests from @TallTed are addressed and we're ok with Data Integrity being dropped from the title approving this.

2024-05-28 13:24 UTC, BigBlueHat commented
> [assuming] we're ok with Data Integrity being dropped from the title approving this.

This is the kind of feedback I was looking for, so thank you for commenting! I put "Data Integrity" back in the title, but dropped the version number from the report--since we're not updating it there (or at least haven't been).

Thoughts?

2024-06-04 19:02 UTC, TallTed approved these changes

2024-06-07 22:19 UTC, merged