JCS Algorithms file
w3c/vc-di-ecdsa-test-suite pull request #97
Opened 2024-11-11 21:02 UTC by PatStLouis

Adds a couple helper functions and coverage for jcs statements.

2024-11-12 00:34 UTC, TallTed requested changes

2024-11-13 19:04 UTC, aljones15 commented on config/runner.json
> +        "P-256": 64,
double check these proofLengths, but they probably work as is.

2024-11-13 19:47 UTC, aljones15 commented
the tests runs and don't conflict with the other tests so I am marking this ready for review.
It needs to take multiple credentials, but working tests are working tests.

2024-11-13 19:52 UTC, BigBlueHat approved these changes
Great work, as always!

2024-11-13 19:52 UTC, BigBlueHat commented on tests/helpers.js
>      // assume support for vc 1.1
```suggestion
    // assume support for vc 2.0
```

2024-11-13 20:28 UTC, merged